spring.application.name=repository-spring-boot-try

spring.datasource.url=jdbc:mariadb://localhost:3306/book_store
spring.datasource.username=root
spring.datasource.password=kali
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
server.servlet.context-path=api
